"""Seed initial data

Revision ID: 002_seed_initial_data
Revises: 001_initial_migration
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import table, column, String, Integer, Float, Boolean, JSON

# revision identifiers, used by Alembic.
revision = '002_seed_initial_data'
down_revision = '001_initial_migration'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Создаем табличные объекты для вставки данных
    frames_table = table('frames',
        column('id', Integer),
        column('name', String),
        column('description', String),
        column('frame_type', String),
        column('preview_image_url', String),
        column('model_3d_url', String),
        column('camera_settings', JSON),
        column('price', Float),
        column('is_premium', Boolean),
        column('is_active', Boolean),
        column('complexity_level', Integer),
        column('estimated_time_hours', Float),
        column('tags', JSON),
        column('sort_order', Integer)
    )
    
    # Вставляем начальные данные для рамок
    op.bulk_insert(frames_table,
        [
            {
                'id': 1,
                'name': 'Вестерн',
                'description': 'Рамка в стиле дикого запада',
                'frame_type': 'western',
                'preview_image_url': '/static/frames/western_preview.png',
                'model_3d_url': '/static/frames/western.glb',
                'camera_settings': {'minDistance': 10, 'maxDistance': 20, 'initialPosition': [0, 0, 15]},
                'price': 0.0,
                'is_premium': False,
                'is_active': True,
                'complexity_level': 3,
                'estimated_time_hours': 2.5,
                'tags': ['популярные', 'тематические'],
                'sort_order': 1
            },
            {
                'id': 2,
                'name': 'Хэллоуин',
                'description': 'Жутковатая рамка для праздника Хэллоуин',
                'frame_type': 'halloween',
                'preview_image_url': '/static/frames/halloween_preview.png',
                'model_3d_url': '/static/frames/halloween.glb',
                'camera_settings': {'minDistance': 8, 'maxDistance': 18, 'initialPosition': [0, 0, 12]},
                'price': 4.99,
                'is_premium': True,
                'is_active': True,
                'complexity_level': 4,
                'estimated_time_hours': 3.0,
                'tags': ['праздничные', 'премиум'],
                'sort_order': 2
            },
            {
                'id': 3,
                'name': 'Цветы',
                'description': 'Элегантная рамка с цветочными мотивами',
                'frame_type': 'flowers',
                'preview_image_url': '/static/frames/flowers_preview.png',
                'model_3d_url': '/static/frames/flowers.glb',
                'camera_settings': {'minDistance': 6, 'maxDistance': 15, 'initialPosition': [0, 0, 10]},
                'price': 0.0,
                'is_premium': False,
                'is_active': True,
                'complexity_level': 2,
                'estimated_time_hours': 2.0,
                'tags': ['классические', 'женственные'],
                'sort_order': 3
            },
            {
                'id': 4,
                'name': 'Новогодняя',
                'description': 'Праздничная рамка с новогодней тематикой',
                'frame_type': 'christmas',
                'preview_image_url': '/static/frames/christmas_preview.png',
                'model_3d_url': '/static/frames/christmas.glb',
                'camera_settings': {'minDistance': 7, 'maxDistance': 16, 'initialPosition': [0, 0, 11]},
                'price': 3.99,
                'is_premium': True,
                'is_active': True,
                'complexity_level': 3,
                'estimated_time_hours': 2.5,
                'tags': ['праздничные', 'зимние', 'премиум'],
                'sort_order': 4
            },
            {
                'id': 5,
                'name': 'Море',
                'description': 'Рамка с морской тематикой',
                'frame_type': 'sea',
                'preview_image_url': '/static/frames/sea_preview.png',
                'model_3d_url': '/static/frames/sea.glb',
                'camera_settings': {'minDistance': 9, 'maxDistance': 19, 'initialPosition': [0, 0, 14]},
                'price': 0.0,
                'is_premium': False,
                'is_active': True,
                'complexity_level': 2,
                'estimated_time_hours': 2.0,
                'tags': ['природа', 'летние'],
                'sort_order': 5
            },
            {
                'id': 6,
                'name': 'Поп-арт',
                'description': 'Яркая рамка в стиле поп-арт',
                'frame_type': 'popart',
                'preview_image_url': '/static/frames/popart_preview.png',
                'model_3d_url': '/static/frames/popart.glb',
                'camera_settings': {'minDistance': 8, 'maxDistance': 17, 'initialPosition': [0, 0, 12]},
                'price': 5.99,
                'is_premium': True,
                'is_active': True,
                'complexity_level': 4,
                'estimated_time_hours': 3.5,
                'tags': ['современные', 'яркие', 'премиум'],
                'sort_order': 6
            },
            {
                'id': 7,
                'name': 'Дерево',
                'description': 'Натуральная деревянная рамка',
                'frame_type': 'wood',
                'preview_image_url': '/static/frames/wood_preview.png',
                'model_3d_url': '/static/frames/wood.glb',
                'camera_settings': {'minDistance': 10, 'maxDistance': 20, 'initialPosition': [0, 0, 15]},
                'price': 2.99,
                'is_premium': False,
                'is_active': True,
                'complexity_level': 1,
                'estimated_time_hours': 1.5,
                'tags': ['классические', 'натуральные'],
                'sort_order': 7
            },
            {
                'id': 8,
                'name': 'Металл',
                'description': 'Современная металлическая рамка',
                'frame_type': 'metal',
                'preview_image_url': '/static/frames/metal_preview.png',
                'model_3d_url': '/static/frames/metal.glb',
                'camera_settings': {'minDistance': 7, 'maxDistance': 16, 'initialPosition': [0, 0, 11]},
                'price': 4.99,
                'is_premium': True,
                'is_active': True,
                'complexity_level': 3,
                'estimated_time_hours': 2.5,
                'tags': ['современные', 'минимализм', 'премиум'],
                'sort_order': 8
            },
            {
                'id': 9,
                'name': 'Золото',
                'description': 'Роскошная золотая рамка',
                'frame_type': 'gold',
                'preview_image_url': '/static/frames/gold_preview.png',
                'model_3d_url': '/static/frames/gold.glb',
                'camera_settings': {'minDistance': 6, 'maxDistance': 15, 'initialPosition': [0, 0, 10]},
                'price': 7.99,
                'is_premium': True,
                'is_active': True,
                'complexity_level': 5,
                'estimated_time_hours': 4.0,
                'tags': ['роскошные', 'подарочные', 'премиум'],
                'sort_order': 9
            }
        ]
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM frames WHERE id BETWEEN 1 AND 9")
    # ### end Alembic commands ###